---
- name: CREATE DIRECTORY & COPY FILES
  hosts: all
  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: "0755"      

    - name: COPY DOCKERFILE
      copy:
        src: https://github.com/tahatalha/DevopsProject/blob/main/Dockerfile
        dest: /opt/docker

    - name: COPY WAR FILE
      copy:
        src: /var/lib/jenkins/workspace/project-1/webapp/target/webapp.war
        dest: /opt/docker
